name: itch-deploy

on: push

env:
  WORKING_DIRECTORY: .
  CREATE_EXPORTS: 'false'
  GODOT_VERSION: '4.5'

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create export directory
        run: mkdir html5

      - name: Godot HTML5 export
        uses: dulvui/godot-4-html-export@v1.0.2
        with:
          working-directory: $WORKING_DIRECTORY
          godot-version: 4.5
          godot-channel: stable

      # Uploads to itch.io
      #   more info here https://github.com/dulvui/itchio-butler-upload
      - name: Upload to itch.io
        uses: Kwpa/itchio-butler-upload@v0.0.2
        with:
          working-directory: build/html
          api-key: ${{ secrets.ITCH_API_KEY }}
          user: ${{ secrets.USERNAME }}
          game: ${{ secrets.GAMENAME }}
          channel: html5
